---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: quay.io/projectquay/golang:1.21
    steps:
      - uses: actions/checkout@v4
      - run: go test ./...
