---
name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch: {}


jobs:
  build:
    name: Build and push container
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: cli.Dockerfile
          push: true
          tags: quay.io/projectquay/clair-action:$(basename "${GITHUB_REF}")
      - name: Update Dockerfile
        shell: bash
        run: |
          sed -i 's/clair-action:v.*/clair-action:$(basename "${GITHUB_REF}")/' Dockerfile
      - name: Create PR to update version
        uses: peter-evans/create-pull-request@v4.1.4
        with:
          title: "$(basename ${GITHUB_REF}) Dockerfile update"
          body: "This is an automated changelog commit."
          commit-message: "chore: $(basename ${GITHUB_REF}) Dockerfile update"
          branch: "update-$(basename ${GITHUB_REF})"
          signoff: true
          delete-branch: true
